In [1]:
import pandas as pd
import numpy as np
import gzip
import csv

# User Monitoring Pipeline:

### Create Tables in the AWS instance

In [2]:
# Use the following SQL code in MySQL Workbench in order to create the following tables in the User_Monitoring database:
# 1) ucs: two fields [uuid, score] --> [user's unique identifier, and their current UCS score]
# 2) task_scores: four fields [ts, quiz_task_uuid, user_uuid, task_score] -->
#                             [time stamp, task identifier, user's unique identifier, task_score]
# 3) datahunt_tracker: two fields [datahunt_id, num_rows_processed] --> 
#                                 [datahunt's unique id, number of rows in the datahunt that we processed already]
"""

CREATE DATABASE User_Monitoring;

USE User_Monitoring;

CREATE TABLE ucs (
	uuid CHAR,
    score DECIMAL(6,5) NOT NULL
);

desc UCS;

SELECT * FROM UCS;

----------------
CREATE TABLE task_scores (
	ts TIMESTAMP,
    quiz_task_uuid INT,
    user_uuid INT,
    task_score DECIMAL(6,5)
);

desc task_scores;

SELECT * FROM task_scores;


----------------
CREATE TABLE datahunt_tracker (
	datahunt_id INT,
    num_rows_processed INT
);

desc datahunt_tracker;

SELECT * FROM datahunt_tracker;


"""

'\n\nCREATE DATABASE User_Monitoring;\n\nUSE User_Monitoring;\n\nCREATE TABLE ucs (\n\tuuid CHAR,\n    score DECIMAL(6,5) NOT NULL\n);\n\ndesc UCS;\n\nSELECT * FROM UCS;\n\n----------------\nCREATE TABLE task_scores (\n\tts TIMESTAMP,\n    quiz_task_uuid INT,\n    user_uuid INT,\n    task_score DECIMAL(6,5)\n);\n\ndesc task_scores;\n\nSELECT * FROM task_scores;\n\n\n----------------\nCREATE TABLE datahunt_tracker (\n\tdatahunt_id INT,\n    num_rows_processed INT\n);\n\ndesc datahunt_tracker;\n\nSELECT * FROM datahunt_tracker;\n\n\n'

### Create handler functions to interact with AWS instance

In [10]:
# Install pymysql in the current Jupyter kernel
import sys
# !conda install --yes --prefix {sys.prefix} pymysql
!pip install -t $PWD pymysql
import pymysql
import time
# 1. Install pymysql to local directory
# pip install -t $PWD pymysql

# 2. Write code, then zip it up

# Lambda Permissions:
# AWSLambdaVPCAccessExecutionRole

# Configuration Files
endpoint = 'user-monitoring-database.crnwwfmibeif.us-west-1.rds.amazonaws.com'
username = 'admin'
password = 'user_monitoring'
database_name = 'User_Monitoring'

# Connection
connection = pymysql.connect(
    host=endpoint, user=username, passwd=password, db=database_name)
cursor = connection.cursor()

def lambda_handler(event=None, context=None):
    insert_into_table(event['table'])

def table_to_df(table):
    cursor = connection.cursor()
    cursor.execute('SELECT * from {}'.format(table))
    rows = cursor.fetchall()
    field_names = [i[0] for i in cursor.description]
    df = pd.DataFrame(columns=field_names)
    for row in rows:
        df.loc[len(df.index)] = row
    return df

def display_table(table):
    df = table_to_df(table)
    print(table)
    display(df)

def table_to_csv(table):
    df = table_to_df(table)
    df.to_csv(f'{table}.csv', index=False)

def insert_into_table(table, df):
    """
    TODO: modify function to be dynamic. take in table name to insert into as well
          as dataframe to add into the selected table. add data validation to make sure
          df is correctly formatted for table
    """
    cursor = connection.cursor()
    mysql_query = None
    if table == "ucs":
        # df columns: 'contributor_uuid, score'
        
        insert_ucs = "INSERT INTO `ucs` (`uuid`, `score`) VALUES (%s, %s)"
        def ucs_query(row):
            data_ucs = (row['contributor_uuid'], row['score'])
            cursor.execute(insert_ucs, data_ucs)
            return row
        mysql_query = ucs_query
        
        # cursor.execute('SELECT * from ucs')
    elif table == "task_scores":
        # df columns: 'quiz_task_uuid, contributor_uuid, score'
        
        insert_task_scores = "INSERT INTO task_scores (ts, quiz_task_uuid, user_uuid, task_score) VALUES (%s, %s, %s, %s)"  
        def task_scores_query(row):
            ts = time.strftime("%Y-%m-%d %H:%M:%S")
            quiz_task_uuid = row['quiz_task_uuid']
            contributor_uuid = row['contributor_uuid']
            score = row['score']
            data_task_scores = (ts, quiz_task_uuid, contributor_uuid, score)
            cursor.execute(insert_task_scores, data_task_scores)
            return row
        mysql_query = task_scores_query
        
        # cursor.execute('SELECT * from task_scores')
    elif table == "datahunt_tracker":
        # df columns: 'datahunt_id, num_rows_processed'
        
        insert_datahunt_tracker = "INSERT INTO datahunt_tracker (datahunt_id, num_rows_processed) VALUES (%s, %s)"
        def datahunt_tracker_query(row):
            datahunt_id = row['datahunt_id']
            num_rows_processed = row['num_rows_processed']
            data_datahunt_tracker = (datahunt_id, num_rows_processed)
            cursor.execute(insert_datahunt_tracker, data_datahunt_tracker)
            return row
        
        # cursor.execute('SELECT * from datahunt_tracker')
    
    # run the appropriate query on each row of the given dataframe
    df = df.apply(mysql_query, axis=1)
    connection.commit()
    display_table(table)

def clear_table(table):
    cursor = connection.cursor()
    if table == 'ucs':
        truncate = "TRUNCATE TABLE `ucs`"
    elif table == 'task_scores':
        truncate = "TRUNCATE TABLE `task_scores`"
    elif table == 'datahunt_tracker':
        truncate = "TRUNCATE TABLE `datahunt_tracker`"
    cursor.execute(truncate)
    display_table(table)
    connection.commit()
    
def create_table(table):
    cursor = connection.cursor()
    if table == 'ucs':
        create = "CREATE TABLE `ucs` (`uuid` TINYTEXT, `score` DECIMAL(6,5) NOT NULL)"
    elif table == 'task_scores':
        create = "CREATE TABLE `task_scores` ( \
                                `ts` TIMESTAMP, \
                                `quiz_task_uuid` INT, \
                                `user_uuid` TINYTEXT, \
                                `task_score` DECIMAL(6,5) \
                                )"
    elif table == 'datahunt_tracker':
        create = "CREATE TABLE `datahunt_tracker` ( \
                                `datahunt_id` TINYTEXT, \
                                `num_rows_processed` INT \
                                )"
        
    cursor.execute(create)
    display_table(table)
    connection.commit()

def remake_table(table=None):
    cursor = connection.cursor()
    if table == 'ucs':
        drop = "DROP TABLE `ucs`"
        create = "CREATE TABLE `ucs` (`uuid` TINYTEXT, `score` DECIMAL(6,5) NOT NULL)"
    elif table == 'task_scores':
        drop = "DROP TABLE `task_scores`"
        create = "CREATE TABLE `task_scores` ( \
                                `ts` TIMESTAMP, \
                                `quiz_task_uuid` TINYTEXT, \
                                `user_uuid` TINYTEXT, \
                                `task_score` DECIMAL(6,5) \
                                )"
    elif table == 'datahunt_tracker':
        drop = "DROP TABLE `datahunt_tracker`"
        create = "CREATE TABLE `datahunt_tracker` ( \
                                `datahunt_id` TINYTEXT, \
                                `num_rows_processed` INT \
                                )"
        
    cursor.execute(drop)
    cursor.execute(create)
    display_table(table)
    connection.commit()
    
def remake_all_tables():
    remake_table('ucs')
    remake_table('task_scores')
    remake_table('datahunt_tracker')
    connection.commit()

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting pymysql
  Using cached PyMySQL-1.0.2-py3-none-any.whl (43 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.0.2

### Function to load in data from /evidence_eric

In [4]:
def load_data(filename):
    df = pd.read_csv(filename)
    return df

### Creating Task Scores
This part of the notebook will include steps 2 and 3 from the User Monitoring Pipeline, which includes identifying the consensus answer from the IAA and Gold Standard data (step 2) and creating the corresponding task scores for users who completed this task (step 3).

## Hardcoded Evidence Schema
Most of this information will be in some sort of schema file (see file 'Evidence2021_05_19-Schema.csv'), but I'm not sure where the schema file is for this specific set of tasks. Thus, I hard coded it with the schema data from https://github.com/Goodly/PEUserMonitoring/blob/master/task-schema/Evidence.txt. Getting this information with the right schema file should be fairly straightforward.

__TODO__: Get schema file and implement method to retrieve the set of scored questions as well as a nested dictionary represented the question schema.

In [7]:
scored_questions = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

question_schema = {1:{'type':'select_one_nominal', 'num_choices':3},
           2:{'type':'select_all', 'num_choices':9},
           3:{'type':'select_one_nominal', 'num_choices':1},
           4:{'type':'select_one_ordinal', 'num_choices':6},
           5:{'type':'select_one_nominal', 'num_choices':5},
           6:{'type':'select_one_nominal', 'num_choices':3},
           7:{'type':'select_one_ordinal', 'num_choices':1},
           8:{'type':'select_one_ordinal', 'num_choices':5},
           9:{'type':'select_one_ordinal', 'num_choices':3},
           10:{'type':'select_one_ordinal', 'num_choices':5},
           11:{'type':'select_one_ordinal', 'num_choices':5},
           12:{'type':'select_one_ordinal', 'num_choices':4},
           13:{'type':'select_one_ordinal', 'num_choices':10},
           14:{'type':'select_one_ordinal', 'num_choices':10}}

## Preprocessing of IAA and Gold Standard Data

In [8]:
# read in the data
adjudicated = pd.read_csv('evidence_eric/evidence_eric/Covid_Evidence2020_03_21.adjudicated-edb1510f-1923-4d6f-a678-95f53d752bea-Tags.csv')
iaa = pd.read_csv('evidence_eric/evidence_eric/Covid_Evidencev1.IAA-edb1510f-1923-4d6f-a678-95f53d752bea-Tags.csv')

# getting rid of some rows where the answer was invalid, probably represents some other metadata
iaa = iaa[iaa.answer_uuid.str.len() > 3]

In [9]:
# these are the only relevant columns for scoring for now, notice highlight data is not included here
cols = ['answer_uuid', 'question_Number', 'agreed_Answer']

# getting rid of some rows where the above columns were the same, this may represent different 
# highlights for the same question and answer?
adjudicated = adjudicated[cols].drop_duplicates()
iaa = iaa[cols].drop_duplicates()

Below cells just show the format of the preprocessed IAA and Adjudicated / Gold Standard data.

In [10]:
adjudicated.head(3)

                            answer_uuid  question_Number  agreed_Answer
0  73d7a14a-9ec6-404c-b2b7-a55508af3b76                1              1
1  5a1fb1f4-d8b7-45c0-bce5-7d4c3b91c55f                2              1
3  ba2d1638-2509-4ce8-9130-39ea26d1d424                2              2

In [11]:
iaa.head(3)

                            answer_uuid  question_Number agreed_Answer
0  73d7a14a-9ec6-404c-b2b7-a55508af3b76                1             1
3  5a1fb1f4-d8b7-45c0-bce5-7d4c3b91c55f                2             1
4  ba2d1638-2509-4ce8-9130-39ea26d1d424                2             2

## Creating The Answer Key

In [12]:
# consensus answer key
consensus_answers = {}

def get_answer(question, answer_source):
    """
    Take in the question and the answer_source, either IAA or Adjudicated / Gold Standard, and adds the
    converged consensus answer to the consensus_answer answer key. This will be an single
    int for select_one questions, or a list of ints for select_all questions.
    """
    question_type = question_schema[question]['type']
    
    if question_type == 'select_one_nominal' or question_type == 'select_one_ordinal':
        assert len(answer_source[answer_source.question_Number == question].agreed_Answer) == 1
        consensus_answers[question] = answer_source[answer_source.question_Number == question].agreed_Answer.iloc[0]
    elif question_type == 'select_all':
        consensus_answers[question] = list(answer_source[answer_source.question_Number == question].agreed_Answer)
    else:
        raise ValueError('Invalid question type')

In [13]:
# create a set of questions that the Adjudicated / Gold Standard data determined converged to a consensus
adjudicated_consensus_questions = set(adjudicated.question_Number)

# create a set of questions that the IAA data determined converged to a consensus
iaa_consensus_questions = set(iaa.question_Number)

# uses get_answer function to fill in the consensus_answers answer key
for question in scored_questions:
    if question in adjudicated_consensus_questions:
        get_answer(question, adjudicated)
    elif question in iaa_consensus_questions:
        get_answer(question, iaa)
    else:
        consensus_answers[question] = -1

What the consensus key looks like:

In [14]:
consensus_answers

{1: 1,
 2: [1, 2, 3, 5],
 3: -1,
 4: 2,
 5: 5,
 6: '3',
 7: 1,
 8: 4,
 9: 1,
 10: 4,
 11: 4,
 12: 2}

## Scoring Users

In [15]:
def scoring_select_one_nominal(question, answer):
    """
    Takes in a question and the selected answer, returns a score of 0 if the consensus 
    answer is different, and 1 if the consensus answer is the same.
    """
    consensus_answer = consensus_answers[question]
    return int(consensus_answer == answer)

In [16]:
def scoring_select_one_ordinal(question, answer):
    """
    Takes in a question and the selected answer, returns a score between 0 and 1 depending
    on how far off the answer is from the consensus answer.
    """
    consensus_answer = consensus_answers[question]
    num_choices = question_schema[question]['num_choices']
    return 1 - (abs(answer - consensus_answer) / num_choices)

In [17]:
def scoring_select_all(question, answer_list):
    """
    Takes in a question and the selected answer, returns a score between 0 and 1 depending
    on the accuracy ((True Positive + True Negative) / Total) of the answer selections
    compared to the consensus answer selections.
    """
    answer_set = set(answer_list)
    consensus_answer_set = set(consensus_answers[question])
    num_choices = question_schema[question]['num_choices']
    
    total_correct = 0
    for answer in range(1, num_choices+1):
        if (answer in answer_set) and (answer in consensus_answer_set):
            total_correct += 1
        elif (answer not in answer_set) and (answer not in consensus_answer_set):
            total_correct += 1
        else:
            total_correct += 0
        
    return total_correct / num_choices

In [18]:
def scoring(row):
    """
    This is a Pandas apply function, to be applied on axis=1 (on each row).
    Makes a call to one of scoring_select_one_nominal, scoring_select_one_ordinal, and
    scoring_select_all depending on the type of question, returns the outputted score.
    
    An important note is that right now if neither IAA nor Gold Standard have a consensus
    answer for a question, the consensus_answers answer key will contain a -1 for that 
    question. I currently assume this question should not have been answered due to it
    being a child-question from an incorrectly answered parent question, so I score it
    """
    question = int(row['question_label'])
    answer_list = [int(i) for i in row['answer_label']]
    
    if consensus_answers[question] == -1:
        return 0
    
    question_type = question_schema[question]['type']
    if question_type == 'select_one_nominal':
        return scoring_select_one_nominal(question, answer_list[0])
    elif question_type == 'select_one_ordinal':
        return scoring_select_one_ordinal(question, answer_list[0])
    elif question_type == 'select_all':
        return scoring_select_all(question, answer_list)
    else:
        raise ValueError('Invalid question type')

In [19]:
# read in the datahunt
df_full = pd.read_csv('evidence_eric/evidence_eric/Covid_Evidencev1-Task-2224-DataHunt.csv')

In [20]:
df_full

,namespace,schema_sha256,quiz_task_uuid,task_url,tua_uuid,article_batch_name,article_number,article_filename,article_sha256,article_text_length,...,answer_label,answer_content,answer_uuid,submitted_tua_uuid,answer_text,case_number,highlight_count,start_pos,end_pos,target_text
0,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q1.A1,"General Causation (In general, X causes Y.)",73d7a14a-9ec6-404c-b2b7-a55508af3b76,50a87210-bcda-459b-9be6-5587a1459012,"General Causation (In general, X causes Y.)",1,1,7,57,Social distancing comes with psychological fal...
1,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q2.A1,Correlation,5a1fb1f4-d8b7-45c0-bce5-7d4c3b91c55f,09412d04-f88d-4328-a8c0-556bdc47d669,Correlation,1,1,1401,1937,Many\xa0quarantined individuals experienced bo...
2,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q2.A2,Cause precedes effect,ba2d1638-2509-4ce8-9130-39ea26d1d424,b1f0cf0f-a6ae-4fb1-8e6d-551b652c88f4,Cause precedes effect,1,1,1213,1266,psychological outcomes of people who were quar...
3,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q2.A3,The correlation appears across multiple indepe...,fee5e5ec-ce13-43e7-aca6-5babee4eb8a5,170e0c43-a9f0-447c-aa35-4be7864e1dcf,The correlation appears across multiple indepe...,1,1,1326,1399,"SARS, H1N1 flu, Ebola and other infectious dis..."
4,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q4.A6,Can't tell; not enough info,7369a857-fd09-4a36-8e26-e64e8d5a6641,44fc7d46-3135-41c9-a2ee-244e76de09af,Can't tell; not enough info,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q10.A5,Very Unlikely,443d94fe-c0a2-4a8b-819f-9253a570f788,d0db2afe-8fba-4f2a-b0fc-86a9182a2627,Very Unlikely,0,0,0,0,NaN
769,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q11.A4,Somewhat Unlikely,6a8b58aa-2748-4697-995b-c1a34149f70d,c934c5a4-eb4d-4fa5-9d7c-411d5d566b14,Somewhat Unlikely,0,0,0,0,NaN
770,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q12.A2,"Yes, implicitly",a0972088-cb65-4764-a4ee-3be2b2bd100a,bcb8cfd5-5a02-4c96-babe-8af03b0fa1e9,"Yes, implicitly",1,1,1023,1106,Research on the psychological toll of social d...
771,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q13.A6,6,c296eb9d-def0-4a2e-91a4-f27215a4333c,3f7c3cfe-c478-4d76-a21a-d22e005c96a1,6,0,0,0,0,NaN
772,Covid_Evidence2020_03_21,45dce5251bd3ea6e908fa33ac9e6a8e17e6830215912ce...,edb1510f-1923-4d6f-a678-95f53d752bea,https://pe.goodlylabs.org/project/Covid_Eviden...,a723537a-f11a-41dd-bf5b-668cef67a5de,CovidArticles/Covid_article_for_PE_S&S&S.txt,100059,Covid_article_for_PE_S&S&S.txt,4b537e0ed21179a29ed28da28057d338e67330ae12123c...,6794,...,T1.Q14.A9,9,8193d6e2-9ccb-4993-a130-bfcc7c99dd85,0a6626fd-91fe-49e6-a76b-0cae2813f342,9,0,0,0,0,NaN

In [21]:
# narrow down the datahunt to the relevant columns for scoring, getting rid of some rows
# where the data for the below columns were the same, this may represent different highlights 
# for the same question and answer? not certain.
df = df_full[['contributor_uuid', 'question_label', 'answer_label']].drop_duplicates()

# the question and answer labels in the datahunt are in the form 'T1.QX' and 'T1.QX.AX'
# the below lines strip down to only question number and answer number
df['question_label'] = df['question_label'].str.split('Q').str[1].astype(int)
df['answer_label'] = df['answer_label'].str.split('A').str[1]

In [22]:
df

                         contributor_uuid  question_label answer_label
0    e1ae8875-a398-4dde-8f4e-4b21109784e3               1            1
1    e1ae8875-a398-4dde-8f4e-4b21109784e3               2            1
2    e1ae8875-a398-4dde-8f4e-4b21109784e3               2            2
3    e1ae8875-a398-4dde-8f4e-4b21109784e3               2            3
4    e1ae8875-a398-4dde-8f4e-4b21109784e3               4            6
..                                    ...             ...          ...
768  bd786026-bad5-4fa8-9a3a-38ca03a16412              10            5
769  bd786026-bad5-4fa8-9a3a-38ca03a16412              11            4
770  bd786026-bad5-4fa8-9a3a-38ca03a16412              12            2
771  bd786026-bad5-4fa8-9a3a-38ca03a16412              13            6
772  bd786026-bad5-4fa8-9a3a-38ca03a16412              14            9

[641 rows x 3 columns]

In [23]:
# we want to groupby contributor_uuid and question_label to get all the answers a user
# selected for a particular question, to account for select_all questions. Now, the
# granularity of df_grouped will be one row per contributor answering a question.
df_grouped = df.groupby(['contributor_uuid', 'question_label']).agg(list).reset_index()

In [24]:
df_grouped

                         contributor_uuid  question_label  answer_label
0    00f548b7-6b63-4b47-828e-8e416b6ca0e2               1           [1]
1    00f548b7-6b63-4b47-828e-8e416b6ca0e2               2  [3, 5, 8, 4]
2    00f548b7-6b63-4b47-828e-8e416b6ca0e2               3           [1]
3    00f548b7-6b63-4b47-828e-8e416b6ca0e2               4           [6]
4    00f548b7-6b63-4b47-828e-8e416b6ca0e2               5           [2]
..                                    ...             ...           ...
549  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              10           [4]
550  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              11           [4]
551  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              12           [2]
552  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              13           [2]
553  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              14           [7]

[554 rows x 3 columns]

In [25]:
# we only want to score the rows with scored questions (not survey questions like 13 and 14)
# so we'll filter those out
df_grouped = df_grouped[df_grouped.question_label.isin(scored_questions)]

In [26]:
df_grouped

                         contributor_uuid  question_label  answer_label
0    00f548b7-6b63-4b47-828e-8e416b6ca0e2               1           [1]
1    00f548b7-6b63-4b47-828e-8e416b6ca0e2               2  [3, 5, 8, 4]
2    00f548b7-6b63-4b47-828e-8e416b6ca0e2               3           [1]
3    00f548b7-6b63-4b47-828e-8e416b6ca0e2               4           [6]
4    00f548b7-6b63-4b47-828e-8e416b6ca0e2               5           [2]
..                                    ...             ...           ...
547  fd6f6837-7881-4943-8129-b7ea0f0fe1b6               8           [5]
548  fd6f6837-7881-4943-8129-b7ea0f0fe1b6               9           [1]
549  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              10           [4]
550  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              11           [4]
551  fd6f6837-7881-4943-8129-b7ea0f0fe1b6              12           [2]

[440 rows x 3 columns]

In [27]:
# using the scoring function defined above, we'll create a new column containing the scores
# for each contributor answering a question.
df_grouped['score'] = df_grouped.apply(scoring, axis=1)

/var/folders/lm/c8rqgf352bv284_6j3cg9jt80000gn/T/ipykernel_5114/2111373349.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_grouped['score'] = df_grouped.apply(scoring, axis=1)

This is the current format of df_grouped.

In [28]:
df_grouped.head(3)

,contributor_uuid,question_label,answer_label,score
0,00f548b7-6b63-4b47-828e-8e416b6ca0e2,1,[1],1.000000
1,00f548b7-6b63-4b47-828e-8e416b6ca0e2,2,"[3, 5, 8, 4]",0.555556
2,00f548b7-6b63-4b47-828e-8e416b6ca0e2,3,[1],0.000000

In [29]:
# lastly, we want to get the average score for all task responses, this will be their
# task score. this is done by a simple groupby on contributor_uuid and mean() aggregate function
calculated_task_scores = df_grouped[['contributor_uuid', 'score']].groupby('contributor_uuid').mean().reset_index()

In [31]:
quiz_task_uuid = df_full['quiz_task_uuid'][0]
quiz_task_uuid

'edb1510f-1923-4d6f-a678-95f53d752bea'

In [32]:
rows_processed = len(df_full)
rows_processed

773

This is what the final task_scores output will look like:

In [33]:
calculated_task_scores['quiz_task_uuid'] = quiz_task_uuid
calculated_task_scores

,contributor_uuid,score,quiz_task_uuid
0,00f548b7-6b63-4b47-828e-8e416b6ca0e2,0.603241,edb1510f-1923-4d6f-a678-95f53d752bea
1,070268de-067c-463b-9ad3-5c88292d881e,0.878889,edb1510f-1923-4d6f-a678-95f53d752bea
2,082a8363-a579-41b4-8918-c166fec3a3a4,0.513333,edb1510f-1923-4d6f-a678-95f53d752bea
3,09df3ada-e5a8-4419-b78a-e0d1e9b37484,0.277778,edb1510f-1923-4d6f-a678-95f53d752bea
4,09f279ac-1c34-4a84-8972-3d92b93605a7,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
5,0c22ce7c-4641-4bb1-97f4-7a7355f70f25,0.831481,edb1510f-1923-4d6f-a678-95f53d752bea
6,0e51ab2d-1a03-4d18-be33-fd21a829d19b,0.754630,edb1510f-1923-4d6f-a678-95f53d752bea
7,1b69eee8-ab95-49dd-8979-9fff7655964d,0.277778,edb1510f-1923-4d6f-a678-95f53d752bea
8,21ffd986-c219-43a0-b82f-4cc460da628d,0.831481,edb1510f-1923-4d6f-a678-95f53d752bea
9,24640f45-b90b-40dc-a848-9e03fdfbbf91,0.588889,edb1510f-1923-4d6f-a678-95f53d752bea
10,2658cecf-829f-4b91-84fa-333e1ff2533c,0.574537,edb1510f-1923-4d6f-a678-95f53d752bea
11,2de6fa3e-ba77-4247-97a1-ce5661997618,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
12,3254f476-8fe5-4b93-8ab3-0a858015fde1,0.597475,edb1510f-1923-4d6f-a678-95f53d752bea
13,348c9e41-2d9c-47fa-b13c-3ec96d70afcc,0.817284,edb1510f-1923-4d6f-a678-95f53d752bea
14,38843a0b-310a-4083-920e-4c7431c085d9,0.789899,edb1510f-1923-4d6f-a678-95f53d752bea
15,3de829c9-4cc0-42b6-a29b-f4d8dcb861a3,0.690909,edb1510f-1923-4d6f-a678-95f53d752bea
16,411f7dff-e994-433c-b5c6-a7d4adf9b010,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
17,5059cbd7-64ee-48c0-8942-583f9e6c67c2,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
18,51f195d5-1362-4a7e-9d72-3aa9ff3c437d,0.712222,edb1510f-1923-4d6f-a678-95f53d752bea
19,62b8fd1c-9cd2-4a31-a8a1-0641d5b8dc71,0.736869,edb1510f-1923-4d6f-a678-95f53d752bea
20,6d82de9d-0553-47b6-b678-d0110a069663,0.593750,edb1510f-1923-4d6f-a678-95f53d752bea
21,6e035130-fe33-4c6b-8712-1aefc4bc68de,0.514815,edb1510f-1923-4d6f-a678-95f53d752bea
22,7c99c1f8-6853-409c-a6c4-124bdfb6489f,0.753968,edb1510f-1923-4d6f-a678-95f53d752bea
23,85579cf2-e01c-45c5-b9e7-34b40467148d,0.828571,edb1510f-1923-4d6f-a678-95f53d752bea
24,8f5c408e-20c1-4f79-ac52-bb772dff6b32,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
25,90f54517-9a8b-43d1-9ea1-95ba35b465d4,0.277778,edb1510f-1923-4d6f-a678-95f53d752bea
26,95dc40d9-3710-47d7-abf0-24b825a1d0c5,0.890741,edb1510f-1923-4d6f-a678-95f53d752bea
27,981874cf-9246-4e1e-b23c-00d432126c4f,0.875309,edb1510f-1923-4d6f-a678-95f53d752bea
28,a1646881-e64e-4139-b608-f4d4a42de866,0.604938,edb1510f-1923-4d6f-a678-95f53d752bea
29,a2edb56d-11a9-4823-93c7-260e11d36668,0.678395,edb1510f-1923-4d6f-a678-95f53d752bea
30,a5a60ffa-d84a-46f1-9011-38515d1c249e,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
31,ac49bd61-73d3-475b-9dcd-e8f476c0c19b,0.766667,edb1510f-1923-4d6f-a678-95f53d752bea
32,ace2c639-8cd5-403e-8b0e-1af7faddf349,0.597475,edb1510f-1923-4d6f-a678-95f53d752bea
33,b3d267dc-896f-4bc9-8f9b-a6a942db579a,0.636364,edb1510f-1923-4d6f-a678-95f53d752bea
34,ba750de9-78de-45bb-a929-873704fe71e8,0.752525,edb1510f-1923-4d6f-a678-95f53d752bea
35,bd786026-bad5-4fa8-9a3a-38ca03a16412,0.736364,edb1510f-1923-4d6f-a678-95f53d752bea
36,c0697300-b1e0-48fd-92cd-958aa1b8a4f7,0.850000,edb1510f-1923-4d6f-a678-95f53d752bea
37,c0ab7c63-2f39-405a-97cf-8a0e4161c03e,0.277778,edb1510f-1923-4d6f-a678-95f53d752bea
38,c2ce666b-eb5f-416a-bfea-8125ff5606f3,0.670202,edb1510f-1923-4d6f-a678-95f53d752bea
39,c3a4c4a5-1efe-4554-ab45-60f32737a52d,0.781818,edb1510f-1923-4d6f-a678-95f53d752bea
40,cffa52fe-b6e2-433e-ba12-f36225f8ec5c,0.656566,edb1510f-1923-4d6f-a678-95f53d752bea
41,d50137ad-8dce-4274-85c5-c2b399ce7ae0,0.277778,edb1510f-1923-4d6f-a678-95f53d752bea
42,d5a1b3dc-4247-4f6f-8c2c-a11a4877cf01,0.767172,edb1510f-1923-4d6f-a678-95f53d752bea
43,d77af5c1-a742-4613-9bb6-0260e4945899,0.733333,edb1510f-1923-4d6f-a678-95f53d752bea
44,db8307ca-1d91-4749-b1e5-ac4bb8aba075,0.716162,edb1510f-1923-4d6f-a678-95f53d752bea
45,dc33f0ea-1670-4a8e-80a0-b10aa78bba24,0.937778,edb1510f-1923-4d6f-a678-95f53d752bea
46,de68bbf8-46d7-45f0-9111-92e64ab9499a,0.277778,edb1510f-1923-4d6f-a678-95f53d752bea
47,e1ae8875-a398-4dde-8f4e-4b21109784e3,0.891358,edb1510f-1923-4d6f-a678-95f53d752bea
48,e7042c9b-f64c-4a6a-a8c9-f2cc7fca6866,0.834568,edb1510f-1923-4d6f-a678-95f53d752bea
49,e8542793-c51d-4edd-9f27-f2cb6005ed39,0.686420,edb1510f-1923-4d6f-a678-95f53d752bea
50,eddb3434-036e-4901-a4cf-02b10326e7dc,0.896296,edb1510f-1923-4d6f-a678-95f53d752bea
51,ee0c5dfb-4021-4d7f-b62a-f9830df90514,0.758333,edb1510f-1923-4d6f-a678-95f53d752bea
52,f7ba7233-32f2-4390-b026-16acd43954f0,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
53,f81fbbc0-feb7-454d-b486-c24e17bccad6,0.900617,edb1510f-1923-4d6f-a678-95f53d752bea
54,f9143626-bfe0-4e69-b652-6d1525ab4eb0,0.361111,edb1510f-1923-4d6f-a678-95f53d752bea
55,fc3f3244-1ff1-4e88-b1cd-51368ad5a313,0.933333,edb1510f-1923-4d6f-a678-95f53d752bea
56,fd6f6837-7881-4943-8129-b7ea0f0fe1b6,0.963333,edb1510f-1923-4d6f-a678-95f53d752bea

The below value is the number of rows processed in this datahunt, to be used for updating the datahunt tracking table.

The below value represents an identifier for each datahunt, meaning an identifier for each task since each datahunt corresponds to one task.

## Updating and Retrieving Data from the User-Monitoring Database

In [34]:
# ucs function that reads accepts values from a csv and a current user's ucs score
def ucs_update_score(user_id):
    def logistic(x, k, offset):
        return 1 / (1 + np.e**(-k * (x - offset)))   
    
    cursor = connection.cursor()
    task_scores = table_to_df('task_scores')
    task_scores = task_scores[task_scores['user_uuid'] == user_id]['task_score'].astype('float')
    last_task_score = task_scores.iloc[-1]
    
    a = 1000
    num_task_scores = len(task_scores)
    n = min(10, int(np.sqrt(num_task_scores)) + 1)
    ucs = table_to_df('ucs')
    if num_task_scores == 1: # if this is the user's first task
        cur_ucs = 0.5
        var_scores = np.var(task_scores.iloc[-n:])
        c = logistic(var_scores / (np.log(num_task_scores + 1) / (np.log(a))), 10, 0.2)
        new_ucs = cur_ucs * (1 - c) + (c) * last_task_score
        query = "INSERT INTO `ucs` (`uuid`, `score`) VALUES (%s, %s)"
        cursor.execute(query, (user_id, new_ucs))
    else:
        cur_ucs = ucs[ucs['uuid'] == user_id]['score'].astype('float')[0]
        var_scores = np.var(task_scores.iloc[-n:])
        c = logistic(var_scores / (np.log(num_task_scores + 1) / (np.log(a))), 10, 0.2)
        new_ucs = cur_ucs * (1 - c) + (c) * last_task_score
        query = "UPDATE `ucs` SET `score` = %s WHERE `uuid` = %s"
        cursor.execute(query, (new_ucs, user_id))
    connection.commit()

#### Step 1) Insert calculated_task_scores into the task scores table and check that the task_scores table updated properly

In [ ]:
insert_into_table('task_scores', calculated_task_scores)

#### Step 2) Update User Credibility Score:
Algorithm: Once per row in calculated_task_scores:
1.  if contributor_uuid not in ucs, initialize user in ucs (insert_to_table(ucs)) with baseline score of 0.5
2. call scoring function: takes in calculated_task_scores, calculates c_value, accesses ucs data
3. update ucs table in place

In [58]:
# ucs function that reads accepts values from a csv and a current user's ucs score
def ucs_update_score(user_id):
    def logistic(x, k, offset):
        return 1 / (1 + np.e**(-k * (x - offset)))   
    
    cursor = connection.cursor()
    task_scores = table_to_df('task_scores')
    task_scores = task_scores[task_scores['user_uuid'] == user_id]['task_score'].astype('float')
    last_task_score = task_scores.iloc[-1]
    
    a = 1000
    num_task_scores = len(task_scores)
    n = min(10, int(np.sqrt(num_task_scores)) + 1)
    ucs = table_to_df('ucs')
    if num_task_scores == 1: # if this is the user's first task
        cur_ucs = 0.5
        var_scores = np.var(task_scores.iloc[-n:])
        c = logistic(var_scores / (np.log(num_task_scores + 1) / (np.log(a))), 10, 0.2)
        new_ucs = cur_ucs * (1 - c) + (c) * last_task_score
        query = "INSERT INTO `ucs` (`uuid`, `score`) VALUES (%s, %s)"
        cursor.execute(query, (user_id, new_ucs))
        connection.commit()
    else:
        print('user_id: ', user_id)
        print(ucs[ucs['uuid'] == user_id]['score'].astype('float'))
        cur_ucs = ucs[ucs['uuid'] == user_id]['score'].astype('float')[0]
        var_scores = np.var(task_scores.iloc[-n:])
        c = logistic(var_scores / (np.log(num_task_scores + 1) / (np.log(a))), 10, 0.2)
        new_ucs = cur_ucs * (1 - c) + (c) * last_task_score
        query = "UPDATE `ucs` SET `score` = %s WHERE `uuid` = %s"
        cursor.execute(query, (new_ucs, user_id))
        connection.commit()

In [ ]:
display_table('ucs')

#### Step 3) Whitelisting users who are part of the 4/3 demo program

In [36]:
# pseudocode:

# def load_participants_list(file_name):
#     participants = load_data(file_name)
#     combine the first and the second rows of the participants data as the index
#     https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html
#     drop the second row

# def get_whitelisted_users(participants_list):
#     get ucs scores as df
#     inner merge (?) between ucs scores and participants_list
#     return resulting dataframe, which should already be sorted

#### Step 4) Download the dataframe of whitelisted ucs scores as csv locally

In [37]:
# pseudocode:

# get_whitelisted_users(participants_list)